import os
import torch
import torch.nn as nn
import torchaudio
import torchaudio.transforms as T
from datasets import load_dataset
from torch.utils.data import Dataset
from transformers import AutoProcessor, Wav2Vec2Model

# 1. Dataset Loading Logic (Controls dataset size)
def prepare_dataset(target_per_class=5):
    os.makedirs("dataset/real", exist_ok=True)
    os.makedirs("dataset/cloned", exist_ok=True)
    
    dataset = load_dataset("ashraq/esc50", split="train", streaming=True)
    real_count, fake_count = 0, 0

    for item in dataset:
        audio = item["audio"]
        if real_count < target_per_class:
            sf_write_path = f"dataset/real/real_{real_count}.wav"
            torchaudio.save(sf_write_path, torch.tensor(audio["array"]).unsqueeze(0), audio["sampling_rate"])
            real_count += 1
        elif fake_count < target_per_class:
            sf_write_path = f"dataset/cloned/cloned_{fake_count}.wav"
            torchaudio.save(sf_write_path, torch.tensor(audio["array"]).unsqueeze(0), audio["sampling_rate"])
            fake_count += 1
            
        if real_count >= target_per_class and fake_count >= target_per_class:
            break
    print(f"Dataset ready: {real_count} real, {fake_count} cloned samples.")

# 2. PyTorch Dataset Wrapper with 16kHz Resampling
class AudioDeepfakeDataset(Dataset):
    def __init__(self, file_paths, labels, target_sample_rate=16000, max_duration=4.0):
        self.file_paths = file_paths
        self.labels = labels
        self.target_sample_rate = target_sample_rate
        self.max_samples = int(target_sample_rate * max_duration)

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        waveform, sample_rate = torchaudio.load(self.file_paths[idx])
        if waveform.shape[0] > 1:
            waveform = torch.mean(waveform, dim=0, keepdim=True)
        if sample_rate != self.target_sample_rate:
            waveform = T.Resample(orig_freq=sample_rate, new_freq=self.target_sample_rate)(waveform)

        waveform = waveform.squeeze(0)
        if waveform.shape[0] > self.max_samples:
            waveform = waveform[:self.max_samples]
        else:
            waveform = torch.nn.functional.pad(waveform, (0, self.max_samples - waveform.shape[0]))

        return waveform, torch.tensor(self.labels[idx], dtype=torch.float)

# 3. Baseline Classifier Architecture
class VoiceCloneClassifier(nn.Module):
    def __init__(self):
        super(VoiceCloneClassifier, self).__init__()
        self.layer = nn.Sequential(
            nn.Linear(768, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        return self.layer(x)

if __name__ == "__main__":
    prepare_dataset(target_per_class=5)
import torch.optim as optim
from torch.utils.data import DataLoader

def train_model():
    # Gather sample paths generated by prepare_dataset
    real_files = [os.path.join("dataset/real", f) for f in os.listdir("dataset/real") if f.endswith(".wav")]
    cloned_files = [os.path.join("dataset/cloned", f) for f in os.listdir("dataset/cloned") if f.endswith(".wav")]

    file_paths = real_files + cloned_files
    labels = [0.0] * len(real_files) + [1.0] * len(cloned_files)

    if not file_paths:
        print("No training files found. Run prepare_dataset first.")
        return

    dataset = AudioDeepfakeDataset(file_paths, labels)
    dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

    classifier = VoiceCloneClassifier()
    criterion = nn.BCELoss()
    optimizer = optim.Adam(classifier.parameters(), lr=0.001)

    print("Starting training epoch...")
    classifier.train()
    for batch_idx, (waveforms, batch_labels) in enumerate(dataloader):
        print("Loading Wav2Vec2 feature extractor...")
    processor = AutoProcessor.from_pretrained("facebook/wav2vec2-base-960h")
    feature_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")
    feature_model.eval()

    for batch_idx, (waveforms, batch_labels) in enumerate(dataloader):
        with torch.no_grad():
            inputs = processor(waveforms.numpy(), sampling_rate=16000, return_tensors="pt", padding=True)
            outputs = feature_model(**inputs)
            features = outputs.last_hidden_state.mean(dim=1)

        optimizer.zero_grad()
        preds = classifier(features).squeeze(1)
        loss = criterion(preds, batch_labels)
        loss.backward()
        optimizer.step()

        print(f"Batch {batch_idx+1} Loss: {loss.item():.4f}")

if __name__ == "__main__":
    prepare_dataset(target_per_class=5)
    train_model()
